### PR TITLE
Support :as :byte-array via :body as bytes

### PR DESCRIPTION
**Pull request by ahobson**
I'm working with binary data and thus don't want any conversion to/from String.

### CODE REVIEW

**Comment by myfreeweb** [comment]
Thank you!

**Comment by ahobson** [comment]
Thank you very much.  Would you consider making a release?

**Comment by myfreeweb** [comment]
I haven't really touched Clojure anything in a while… but I guess it's time, yeah :D

By the way, are you interested in becoming a maintainer?

**Comment by ahobson** [comment]
Maintainer?  Little ole' me?  Sure I'd be happy to help out.

**Pull request merged**
