### PR TITLE
Raise respond should work with fake routes

### PR DESCRIPTION
**Pull request by vincentjames501**
To address issue #33

### CODE REVIEW

**Comment by myfreeweb** [comment]
Tests are failing on travis…

**Comment by vincentjames501** [comment]
Hmm, interesting!

```
~/D/P/clj-http-fake (raise-respond) $ lein test-3.x                                                                                                          12:46:59
Performing task 'test' with profile(s): 'latest-3.x,1.5'

lein test clj-http.test.fake

Ran 23 tests containing 36 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'latest-3.x,1.6'

lein test clj-http.test.fake

Ran 23 tests containing 36 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'latest-3.x,1.7'

lein test clj-http.test.fake

Ran 23 tests containing 36 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'latest-3.x,1.8'

lein test clj-http.test.fake

Ran 23 tests containing 36 assertions.
0 failures, 0 errors.
~/D/P/clj-http-fake (raise-respond) $ git push                                                                                                               12:47:49
Everything up-to-date
```

**Comment by vincentjames501** [comment]
Ah I see. We should skip that test for 2.x as it's not applicable

**Comment by myfreeweb** [comment]
Thanks!

**Pull request merged**
